### ISSUE TITLE
issue with pipCmdExtraArgs

### ISSUE THREAD

**Issue by aidinkhosrowshahi** [serverless/serverless-python-requirements#320]
We are using gemfury for external package, it was working before but now we have an issue. FYI we are using AWS codebuild.

serverless.yml

pipCmdExtraArgs:
       - --index-url https://pypi.fury.io/${self:custom.fury_auth}/internal

Error:

Error --------------------------------------------------
 Usage:
 /usr/bin/python3 -m pip install [options] <requirement specifier> ...
 /usr/bin/python3 -m pip install [options] -r <requirements file> ...
 /usr/bin/python3 -m pip install [options] [-e] <vcs project url> ...
 /usr/bin/python3 -m pip install [options] [-e] <local project path> ...
 /usr/bin/python3 -m pip install [options] <archive url/path> ...
 no such option: --index-url https://pypi.fury.io/internal
 For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 Stack Trace --------------------------------------------
 Error:
Usage:
 /usr/bin/python3 -m pip install [options] <requirement specifier> ...
 /usr/bin/python3 -m pip install [options] -r <requirements file> ...
 /usr/bin/python3 -m pip install [options] [-e] <vcs project url> ...
 /usr/bin/python3 -m pip install [options] [-e] <local project path> ...
 /usr/bin/python3 -m pip install [options] <archive url/path> ...
 no such option: --index-url https://pypi.fury.io/utwBWQhtFLEwyNQWhKbu/neurotrack
 at filterCommands.forEach (/codebuild/output/src192221926/src/node_modules/serverless-python-requirements/lib/pip.js:303:13)
 at Array.forEach (<anonymous>)
 at installRequirements (/codebuild/output/src192221926/src/node_modules/serverless-python-requirements/lib/pip.js:290:28)
 at installRequirementsIfNeeded (/codebuild/output/src192221926/src/node_modules/serverless-python-requirements/lib/pip.js:515:3)
 at ServerlessPythonRequirements.installAllRequirements (/codebuild/output/src192221926/src/node_modules/serverless-python-requirements/lib/pip.js:594:29)
From previous event:
 at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:400:22)
 at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:418:17)
 at Deploy.BbPromise.bind.then (/usr/local/lib/node_modules/se

**Comment by khornberg** [comment]
I installed 4.2.5 and everything worked

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
