### ISSUE TITLE
lzmaffi pip install exception on sls package

### ISSUE THREAD

**Issue by egarrett** [serverless/serverless-python-requirements#334]
Hi - when running `sls package` I'm getting the following error when requirements.txt contains lzmaffi.

requirements.txt:
```
cffi==1.12.2
pycparser==2.19
lzmaffi==0.3.0
```

When I run `sls package` (or `sls deploy`), I'm getting the following error:
```
Serverless: Generated requirements from /Users/ergar/Development/lzmaffi-test/requirements.txt in /Users/ergar/Development/lzmaffi-test/.serverless/requirements.txt...
Serverless: Installing requirements from /Users/ergar/Development/lzmaffi-test/.serverless/requirements/requirements.txt ...
Serverless: Docker Image: lambci/lambda:build-python3.6
Serverless: Running docker run --rm -v /Users/ergar/Development/lzmaffi-test/.serverless/requirements\:/var/task\:z -u 0 lambci/lambda\:build-python3.6 python3.6 -m pip install -t /var/task/ -r /var/task/requirements.txt...
 
  Error --------------------------------------------------
 
    Failed building wheel for lzmaffi
  Failed cleaning build dir for lzmaffi
Command "/var/lang/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-n0uwhsga/lzmaffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-oabed0ug/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-1tntkuou" failed with error code 1 in /tmp/pip-install-n0uwhsga/lzmaffi/

 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.14.2
     Serverless Version:     1.39.1
```

When I run `docker run --rm -v /Users/ergar/Development/lzmaffi-test/.serverless/requirements\:/var/task\:z -u 0 lambci/lambda\:build-python3.6 python3.6 -m pip install -t /var/task/ -r /var/task/requirements.txt` directly, I get the following `cffi` error:

```
$ docker run --rm -v /Users/ergar/Development/lzmaffi-test/.serverless/requirements\:/var/task\:z -u 0 lambci/lambda\:build-python3.6 python3.6 -m pip install -t /var/task/ -r /var/task/requirements.txt
Collecting cffi==1.12.2 (from -r /var/task/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/20/f7/87b62a8895bf7c93e907b05b97bc4459c81a38a61151f03a6eae13d863aa/cffi-1.12.2-cp36-cp36m-manylinux1_x86_64.whl (428kB)
Collecting lzmaffi==0.3.0 (from -r /var/task/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/33/ba/8bb07cfa9e6746553765558184583751e3c379939bca360425c903d586a8/lzmaffi-0.3.0.tar.gz
Collecting pycparser==2.19 (from -r /var/task/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
Building wheels for collected packages: lzmaffi, pycparser
  Building wheel for lzmaffi (setup.py): started
  Building wheel for lzmaffi (setup.py): finished with status 'error'
  Complete output from command /var/lang/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-bhm6em5d/lzmaffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-dl5ths8v --python-tag cp36:
  This is lzmaffi version 0.3.0
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-bhm6em5d/lzmaffi/setup.py", line 30, in <module>
      import lzmaffi._lzmamodule2 as ffimod
    File "/tmp/pip-install-bhm6em5d/lzmaffi/lzmaffi/__init__.py", line 29, in <module>
      from ._lzmamodule2 import *
    File "/tmp/pip-install-bhm6em5d/lzmaffi/lzmaffi/_lzmamodule2.py", line 2, in <module>
      from cffi import FFI
  ModuleNotFoundError: No module named 'cffi'
```

My Serverless.yml:

```
service: lzmaffi-test

provider:
  name: aws
  runtime: python3.6

custom:
  pythonRequirements:
    dockerizePip: non-linux
    
functions:
  hello:
    handler: handler.hello
              
plugins:
  - serverless-python-requirements
```

**Comment by pgrzesik** [comment]
Hey 👋 I'm closing this ticket as it looks like it's heavily outdated, we can of course reopen it if needed 👍
